### ISSUE TITLE
请求同步一些github-releases: boost, openmpi, hdf5, cmake

### ISSUE THREAD

**Issue by hebrewsnabla** [nju-lug/NJU-Mirror-Issue#1]
请求同步一些项目的github releases:
https://github.com/boostorg/boost
https://github.com/open-mpi/ompi
https://github.com/HDFGroup/hdf5
https://github.com/Kitware/CMake

**Comment by yaoge123** [comment]
https://mirror.nju.edu.cn/git/boost.git/
https://mirrors.nju.edu.cn/git/open-mpi.git/
https://mirror.nju.edu.cn/git/hdf5.git/
https://mirror.nju.edu.cn/git/CMake.git/
