### ISSUE TITLE
[NOI] New Mirror Other Issue for [/robots.txt]

### ISSUE THREAD

**Issue by moeyork** [nju-lug/NJU-Mirror-Issue#13]
## Note

- [ ] **I understand that irregular questions may be rejected.**
- [ ] I understand that the issue raised here is **not** related to the front-end \ document \ files.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** for some reasons.

## Error Information

镜像站网站根目录缺少[/robots.txt](https://mirror.nju.edu.cn/robots.txt), 可能会导致镜像内容被意外收录。

国内其他镜像站基本都有设置，也许可以作为参考：
- [TUNA (https://mirrors.tuna.tsinghua.edu.cn/robots.txt)](https://mirrors.tuna.tsinghua.edu.cn/robots.txt)
- [LZU (https://mirrors.lzu.edu.cn/robots.txt)](https://mirrors.lzu.edu.cn/robots.txt)
- [USTC (https://mirrors.ustc.edu.cn/robots.txt)](https://mirrors.ustc.edu.cn/robots.txt)

另外请问能否提供中文issue模板？

**Comment by yaoge123** [comment]
感谢提醒 已添加
