### ISSUE TITLE
[MER] Mirror Error Report for [pypi]

### ISSUE THREAD

**Issue by wang-r-j** [nju-lug/NJU-Mirror-Issue#14]
## Note

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

Although the mirror of pypi is synchronized every 5 minutes, some packages don't seem to be up to date. For example, brax 0.2.2 was released a few days ago (https://pypi.org/project/brax/#history), but until today the latest version of brax in the mirror is still 0.2.1 (https://mirror.nju.edu.cn/pypi/web/simple/brax/).

**Comment by yaoge123** [comment]
已修复 正在重新同步中
