### ISSUE TITLE
[MER] Mirror Error Report for gitlab-ce

### ISSUE THREAD

**Issue by idawnlight** [nju-lug/NJU-Mirror-Issue#15]
## Note

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

注意到 `https://mirror.nju.edu.cn/gitlab-ce/yum/el8/` 的上次成功同步时间是 2022.5.10，已经严重落后于官方源，请问是已终止同步还是同步错误？

**Comment by yaoge123** [comment]
已修复 正在同步中
