### ISSUE TITLE
[MER] Mirror Error Report for sourceware

### ISSUE THREAD

**Issue by FlyGoat** [nju-lug/NJU-Mirror-Issue#17]
## Note

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

NJU mirror 当前使用 `rsync://mirrors.kernel.org/sourceware/` 作为sourceware的上游。
在请求将mirrorz列入sourceware官方mirror列表的过程中，官方人员表达希望所有的下游都能使用其官方rsync作为同步上游的诉求，其官方rsync源为：`rsync://sourceware.org/ftp/`。

参见：https://github.com/tuna/issues/issues/1415

**Comment by yaoge123** [comment]
非常感谢，sourceware的上游已改为rsync://sourceware.org/ftp/
