### ISSUE TITLE
Mirror requests

### ISSUE THREAD

**Issue by d-w-x** [nju-lug/NJU-Mirror-Issue#2]
## git mirror (sourcecode)

- scoop:
  - [x] https://github.com/lukesampson/scoop-extras
  - [x] https://github.com/ScoopInstaller/Main
  - [x] https://github.com/TheRandomLabs/scoop-nonportable
  - [x] https://github.com/ScoopInstaller/Versions

## github release (tar.gz, exe etc ...)

- [x] https://github.com/ventoy/Ventoy/releases
- [x] https://github.com/fatedier/frp/releases/
- [x] https://github.com/be5invis/Sarasa-Gothic/releases
- [x] https://github.com/microsoft/PowerToys/releases
- [x] https://github.com/PowerShell/PowerShell/releases

**Comment by LadderOperator** [comment]
- [ ] https://github.com/gephi/gephi/release

**Comment by yaoge123** [comment]
均已添加
