### ISSUE TITLE
[MER] Mirror Error Report for pypi

### ISSUE THREAD

**Issue by lostz** [nju-lug/NJU-Mirror-Issue#20]
## Note

- [x ] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

部分pypi 同步延迟过大，例如 langchain 目标版本已经是0.0.170,mirror 里面版本是0.0.167

**Comment by yaoge123** [comment]
上游有些包有问题导致同步卡主，可以临时用 https://doc.nju.edu.cn/books/35f4a/page/pypi-python-package-index

**Comment by lostz** [comment]
ok

**Comment by yaoge123** [comment]
现在pypi正常了
