### ISSUE TITLE
[MER] Mirror Error Report for FreeBSD-Ports

### ISSUE THREAD

**Issue by ykla** [nju-lug/NJU-Mirror-Issue#21]
freebsd-ports 的 ports.git 似乎有问题，无法正常 git clone。

```
# git clone https://mirrors.nju.edu.cn/freebsd-ports/ports.git /usr/ports
```

------

而且 gitup 无法执行，`gitup` 提示协议不支持：

```
[root@ykla /home/ykla]# gitup -v2 ports
# Host: mirrors.nju.edu.cn
# Port: 443
# Repository Path: /freebsd-ports/ports.git
# Target Directory: /usr/ports
gitup: mirrors.nju.edu.cn does not support the version 2 wire protocol: Protocol not supported
```

配置文件示例：

```
# $FreeBSD$
#
# Default configuration options for gitup.conf.
{
        "defaults" : {                       
                "host"           : "mirrors.nju.edu.cn",
                "port"           : 443,      
#               "proxy_host"     : "",       
#               "proxy_port"     : 0,        
#               "proxy_username" : "",       
#               "proxy_password" : "",       
#               "source_address" : "",       
                "low_memory"     : false,    
                "display_depth"  : 0,        
                "verbosity"      : 1,        
                "work_directory" : "/var/db/gitup",
        },                                   

        "ports" : {
                "repository_path"  : "/freebsd-ports/ports.git",
                "branch"           : "main",
                "target_directory" : "/usr/ports",
                "ignores"          : [],
        },

        "quarterly" : {
                "repository_path"  : "/ports.git",
                "branch"           : "quarterly",

```

**Comment by yaoge123** [comment]
我改了一下配置，您看现在支持么？

**Comment by ykla** [comment]
仍旧不支持。

```
root@ykla:~ # gitup ports
# Host: mirrors.nju.edu.cn
# Port: 443
# Repository Path: /freebsd-ports/ports.git
# Target Directory: /usr/ports
gitup: mirrors.nju.edu.cn does not support the version 2 wire protocol: Protocol not supported
```

**Comment by yaoge123** [comment]
freebsd相关的镜像将在不久的未来更换后端和同步方式与官方保持一致，应该可以比较完善的支持了

**Comment by yaoge123** [comment]
不好意思，刚刚有个地方没有注意。
现在应该可以了吗？虽然有点慢……

$ git clone https://mirrors.nju.edu.cn/freebsd-ports/ports.git
Cloning into 'ports'...
remote: Enumerating objects: 6019847, done.
Receiving objects:  37% (2273838/6019847), 672.75 MiB | 37.95 MiB/s

> 仍旧不支持。
> 
> ```
> root@ykla:~ # gitup ports
> # Host: mirrors.nju.edu.cn
> # Port: 443
> # Repository Path: /freebsd-ports/ports.git
> # Target Directory: /usr/ports
> gitup: mirrors.nju.edu.cn does not support the version 2 wire protocol: Protocol not supported
> ```

**Comment by ykla** [comment]
> 不好意思，刚刚有个地方没有注意。 现在应该可以了吗？虽然有点慢……
> 
> $ git clone https://mirrors.nju.edu.cn/freebsd-ports/ports.git Cloning into 'ports'... remote: Enumerating objects: 6019847, done. Receiving objects: 37% (2273838/6019847), 672.75 MiB | 37.95 MiB/s
> 
> > 仍旧不支持。
> > ```
> > root@ykla:~ # gitup ports
> > # Host: mirrors.nju.edu.cn
> > # Port: 443
> > # Repository Path: /freebsd-ports/ports.git
> > # Target Directory: /usr/ports
> > gitup: mirrors.nju.edu.cn does not support the version 2 wire protocol: Protocol not supported
> > ```

经过测试还是一样的。

**Comment by number201724** [comment]
服务器端的git版本至少需要Git 2.34

**Comment by yaoge123** [comment]
> 服务器端的git版本至少需要2.34或更高

已经升级至2.39.2了

> > 不好意思，刚刚有个地方没有注意。 现在应该可以了吗？虽然有点慢……
> > $ git clone https://mirrors.nju.edu.cn/freebsd-ports/ports.git Cloning into 'ports'... remote: Enumerating objects: 6019847, done. Receiving objects: 37% (2273838/6019847), 672.75 MiB | 37.95 MiB/s
> > > 仍旧不支持。
> > > ```
> > > root@ykla:~ # gitup ports
> > > # Host: mirrors.nju.edu.cn
> > > # Port: 443
> > > # Repository Path: /freebsd-ports/ports.git
> > > # Target Directory: /usr/ports
> > > gitup: mirrors.nju.edu.cn does not support the version 2 wire protocol: Protocol not supported
> > > ```
> 
> 经过测试还是一样的。这里是 gitup 的源码 https://github.com/johnmehr/gitup

不好意思 手边没有FreeBSD的环境

**Comment by ykla** [comment]
> > 服务器端的git版本至少需要2.34或更高
> 
> 已经升级至2.39.2了
> 
> > > 不好意思，刚刚有个地方没有注意。 现在应该可以了吗？虽然有点慢……
> > > $ git clone https://mirrors.nju.edu.cn/freebsd-ports/ports.git Cloning into 'ports'... remote: Enumerating objects: 6019847, done. Receiving objects: 37% (2273838/6019847), 672.75 MiB | 37.95 MiB/s
> > > > 仍旧不支持。
> > > > ```
> > > > root@ykla:~ # gitup ports
> > > > # Host: mirrors.nju.edu.cn
> > > > # Port: 443
> > > > # Repository Path: /freebsd-ports/ports.git
> > > > # Target Directory: /usr/ports
> > > > gitup: mirrors.nju.edu.cn does not support the version 2 wire protocol: Protocol not supported
> > > > ```
> > 
> > 
> > 经过测试还是一样的。这里是 gitup 的源码 https://github.com/johnmehr/gitup
> 
> 不好意思 手边没有FreeBSD的环境

已经可以正常使用了。感谢支持。
