### ISSUE TITLE
[MER] Mirror Error Report for rustup

### ISSUE THREAD

**Issue by fraxinus-ch** [nju-lug/NJU-Mirror-Issue#26]
## 使用NJU_rustup镜像无法更新

问题同[CERNET#115](https://github.com/mirrorz-org/mirrorz-help/issues/115)

## 原因及解决方案

对比各家镜像中的`channel-rust-stable.toml`，发现NJU镜像的19798~19799行如下：

> [pkg.rust-src.target]
> 
> (空)

而至少USTC和TUNA家的对应段落如下（以USTC为例）：

> [pkg.rust-src.target."*"]
> 
> available = true
> 
> url = "https://static.rust-lang.org/dist/2023-10-05/rust-src-1.73.0.tar.gz"
> 
> hash = "6efb21f20258c7e5867ece2ccd8d747b2351e5403a288d4454d26e82d1efadb8"
> 
> xz_url = "https://static.rust-lang.org/dist/2023-10-05/rust-src-1.73.0.tar.xz"
>
> xz_hash = "e587179add7469da7ae38237be7fa9d04c37535a7a75a01772a05e822f2aff71"

其他.toml文件应该也有同样的问题🥵......

请求修改，谢谢！❤

**Comment by yaoge123** [comment]
现在正常了，感谢您找出bug
