### ISSUE TITLE
make this mirror an official F-Droid mirror by posting a privacy policy

### ISSUE THREAD

**Issue by eighthave** [nju-lug/NJU-Mirror-Issue#31]
## Note

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to the front-end \ document \ files.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** for some reasons.

## Error Information

Thanks for your service!  Your mirror has become quite important to many of our users in China.  So I would like to see whether it would be possible for your mirror to have a privacy policy posted.  That is the last requirement that needs to be completed for your mirror to become an official F-Droid mirror.  Then the official client app will automatically use it.  It will be built in.

Here are some privacy policies from our other official mirrors:
* https://plug-mirror.rcac.purdue.edu/info.html
* https://ftp.lysator.liu.se/datahanteringspolicy.txt
* https://ftp.fau.de/datenschutz
* https://ftp.agdsn.de/datenschutz.txt

FYI we're tracking this here: https://gitlab.com/fdroid/admin/-/issues/177

There are Chinese speaking contributors, they can follow up in Chinese if that is helpful.  I don't speak any Chinese, sorry.

**Comment by yaoge123** [comment]
https://mirror.nju.edu.cn/privacypolicy.txt
