### ISSUE TITLE
[MER] Mirror Error Report for github-raw

### ISSUE THREAD

**Issue by CybCom** [nju-lug/NJU-Mirror-Issue#34]
## Note

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

**repo url**: https://mirror.nju.edu.cn/github-raw/ and its sub-directories.
**error inforation**: all subdirs are empty.
**how to reproduce the problem**: just click the link. I noticed this when configuring rosdep.
**ATTENTION**: https://mirror.nju.edu.cn/github-raw/ros/rosdistro/master/rosdep/sources.list.d/20-default.list shoud be generated according to our mirror url, instead of syncing form github.

**Comment by yaoge123** [comment]
Maybe it was under maintenance at the time and should be available now.

**Comment by CybCom** [comment]
now it works. thx
