### ISSUE TITLE
[MER] Mirror Error Report for [Name]

### ISSUE THREAD

**Issue by Pr0pHesyer** [nju-lug/NJU-Mirror-Issue#36]
## Note

- [x ] **I understand that irregular questions may be rejected.**
- [ x] I understand that the issue raised here is **not** related to  the front-end.
- [x ] I have looked it up in opening issue, it's **not** reported by others.
- [x ] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

Parabola GNU/Linux-libre [存在于NJU镜像站中，但是不存在于[官方镜像列表](https://www.parabola.nu/mirrors/)。
建议按照[相关wiki](https://wiki.parabola.nu/Creating_a_mirror)向官方反映以添加至官方镜像列表

**Comment by yaoge123** [comment]
感谢提醒，这个已经给官方发邮件了，最近新增的镜像尽量都给官方申请了进入官方列表了
但是历史的一堆大多数都还没有搞 ε=(´ο｀*)))唉

**Comment by yaoge123** [comment]
已经加入官方镜像列表中了
