### ISSUE TITLE
[MER] Mirror Error Report for [Docker hub]

### ISSUE THREAD

**Issue by honhimW** [nju-lug/NJU-Mirror-Issue#39]
## Note

- [ x ] **I understand that irregular questions may be rejected.**
- [ x ] I understand that the issue raised here is **not** related to  the front-end.
- [ x ] I have looked it up in opening issue, it's **not** reported by others.
- [ x ] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information
Container images pulling error.

```bash
$ podman pull docker.io/getmeili/meilisearch:v1.7.0-rc.2
Error: copying system image from manifest list: determining manifest MIME type
for docker://getmeili/meilisearch:v1.7.0-rc.2: reading manifest sha256:9ce0d80f0654536c7e511bb224d36ec00920075cb3dfb2d8395953f9ca46280d
in docker.nju.edu.cn/getmeili/meilisearch: unknown: Remote Auto Blocked
until 2024-03-08T09:33:18.244Z
```

**Comment by d-w-x** [comment]
现在看起来没问题了，可以重新试试。
