### ISSUE TITLE
[NMR] New Mirror Request for [Joplin]

### ISSUE THREAD

**Issue by JaimeZeng** [nju-lug/NJU-Mirror-Issue#4]
## Note 

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to the front-end.
- [x] I have looked it up in the NJU mirror, it's **not** in there now.
- [x] I have looked it up in opening issue, it's **not** suggested by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for same reasons.
- [x] I'm willing to add an NJU-mirror description to the original repo.

## Github Release

- [x] **My check**: I have known that NJU mirror can only mirror for **latest releases without Source code(.tar.gz or .zip)**, couldn;t mirror for tags
- [x] Desktop: https://github.com/laurent22/joplin/releases/latest
- [x] Mobile: https://github.com/laurent22/joplin-android/releases/latest

**Comment by yaoge123** [comment]
https://mirror.nju.edu.cn/github-release/laurent22/
