### ISSUE TITLE
[MER] Mirror Error Report for [epel]

### ISSUE THREAD

**Issue by xWTF** [nju-lug/NJU-Mirror-Issue#41]
## Note
- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

EPEL repo metadata is missing.

Repo URL: https://mirror.nju.edu.cn/epel/

For this metadata URL: https://mirror.nju.edu.cn/epel/9/Everything/x86_64/repodata/

Various metadata files are missing.

![image](https://github.com/nju-lug/NJU-Mirror-Issue/assets/31540475/890616fb-131d-4ad9-b1d3-5bdd2d04a623)

Screenshot from TUNA:

![image](https://github.com/nju-lug/NJU-Mirror-Issue/assets/31540475/75eaf09d-e309-4574-bda4-a92657169d49)

**Comment by yaoge123** [comment]
今天的同步失败了，现在正在重新同步中

**Comment by yaoge123** [comment]
现在已经同步成功了，您再看看

**Comment by xWTF** [comment]
看起来恢复正常了，感谢。
