### ISSUE TITLE
[MER]  zerotier镜像无法访问

### ISSUE THREAD

**Issue by LSP0123** [nju-lug/NJU-Mirror-Issue#45]
zerotier镜像无法访问
![image](https://github.com/user-attachments/assets/427b9169-c56f-4495-b3f8-caeaa40af21f)

```
正在读取软件包列表... 完成
E: 仓库 “https://mirror.nju.edu.cn/zerotier/debian/jammy jammy Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
```
![image](https://github.com/user-attachments/assets/dc690043-6f43-4170-83f9-263438c270d0)

**Comment by yaoge123** [comment]
已修复，请您再测试一下
