### ISSUE TITLE
[MER] MacPorts源访问失败，且curl提示Timeout [MacPorts]

### ISSUE THREAD

**Issue by xavierlineX** [nju-lug/NJU-Mirror-Issue#46]
## Note
- [X] **I understand that irregular questions may be rejected.**
- [X] I understand that the issue raised here is **not** related to  the front-end.
- [X] I have looked it up in opening issue, it's **not** reported by others.
- [X] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information
描述： MacPorts源更新失败，表现为MacPorts使用curl拉取 [PortFiles](https://mirror.nju.edu.cn/macports/release/tarballs/ports.tar) 提示超时，或提示`502 Bad Gateway`。
网络环境描述：
 - `dig A mirror.nju.edu.cn` => `210.28.130.3`
 - IPv4: `159.226.43.XXX/24`
 - 暂未尝试使用IPv6访问。

**Comment by yaoge123** [comment]
可能当时正在维护，现在试一试是否可以？

**Comment by xavierlineX** [comment]
已重试，无问题。
