### ISSUE TITLE
[MER] Mirror Error Report for freebsd-pkg

### ISSUE THREAD

**Issue by ykla** [nju-lug/NJU-Mirror-Issue#47]
<https://mirrors.nju.edu.cn/freebsd-pkg> 访问不可达。且目前镜像站首页的镜像条目也刷新不出来。

中国电信网络。

**Comment by yaoge123** [comment]
可能当时正在维护，现在试一试是否可以？

**Comment by ykla** [comment]
同步日期看起来落后了 2 个月。

**Comment by ykla** [comment]
看起来正常了。
