### ISSUE TITLE
[MER] Mirror Error Report for docker-ce

### ISSUE THREAD

**Issue by fakeboboliu** [nju-lug/NJU-Mirror-Issue#48]
## Note

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

据前端信息，docker-ce mirror 上次同步成功已经是 2 个月前 了。

**Comment by yaoge123** [comment]
现在重新同步好了
