### ISSUE TITLE
[MER] Mirror Error Report for all git repos

### ISSUE THREAD

**Issue by qianbinbin** [nju-lug/NJU-Mirror-Issue#49]
## Note

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

Looks like all git repos cannot be fetched successfully, e.g.

```sh
$ git clone https://mirrors.nju.edu.cn/git/zsh-autosuggestions.git
Cloning into 'zsh-autosuggestions'...
fatal: repository 'https://mirrors.nju.edu.cn/git/zsh-autosuggestions.git/' not found
$ git clone https://mirror.nju.edu.cn/git/homebrew/brew.git
Cloning into 'brew'...
fatal: repository 'https://mirror.nju.edu.cn/git/homebrew/brew.git/' not found
$ git clone https://mirror.nju.edu.cn/git/brew.git
Cloning into 'brew'...
fatal: repository 'https://mirror.nju.edu.cn/git/brew.git/' not found
```

**Comment by yaoge123** [comment]
已经解决了
