### ISSUE TITLE
[NMR] New Mirror Request for Circle Linux 社区企业级Linux（替代CentOS）

### ISSUE THREAD

**Issue by James6xie** [nju-lug/NJU-Mirror-Issue#5]
## Note 

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to the front-end.
- [x] I have looked it up in the NJU mirror, it's **not** in there now.
- [x] I have looked it up in opening issue, it's **not** suggested by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for same reasons.
- [x] I'm willing to add an NJU-mirror description to the original repo.

## Normal Repo

- [x] url_here: add some information about this repo.

- 名称: CircleLinux
- 介绍如下：
Circle Linux 是国际化社区驱动的开源软件，使命在与努力专注于围绕 Linux 平台提供更强大的开源生态。
提供企业级、生产环境就绪的 Linux 发行版。
Global Community-driven Opensource software effort focus on delivering a robust open source ecosystem around a Linux platform.
bring you Enterprise-grade, Production-ready Linux Distro.
- 官网：www.cclinux.org
- GitHub：https://github.com/circle-linux

- 上游地址与镜像方法 (How to mirror)
rsync -avh rsync://msync.cclinux.org/circle/pub/

**Comment by yaoge123** [comment]
http://mirror.nju.edu.cn/circle/
https://mirror.nju.edu.cn/circle/
rsync://mirror.nju.edu.cn/circle/
