### ISSUE TITLE
[NMR] New Mirror Request for [gentoo-zh]

### ISSUE THREAD

**Issue by peeweep** [nju-lug/NJU-Mirror-Issue#50]
## Note 

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to the front-end.
- [x] I have looked it up in the NJU mirror, it's **not** in there now.
- [x] I have looked it up in opening issue, it's **not** suggested by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.
- [x] I'm willing to add an NJU-mirror description to the original repo.

## Normal Repo

- [ ] `rsync://distfiles.gentoocn.org/gentoo-zh`: gentoo-zh distfiles mirror
- [ ] `https://distfiles.gentoocn.org/`: gentoo-zh distfiles mirror

Hi, 我看到 nju mirror 已经提供了 [gentoo-zh.git mirror](https://mirror.nju.edu.cn/git/gentoo-zh.git/)，现在申请添加 gentoo-zh 的 distfiles mirror，可以用 rsync 地址作为镜像的上游。
distfiles.gentoocn.org 用于缓存 [gentoo-zh overlay](https://github.com/microcai/gentoo-zh) 编译所需的 distfiles，类似于 gentoo 的 [distfiles mirror](https://mirror.nju.edu.cn/gentoo/distfiles/)

**Comment by yaoge123** [comment]
正在初始同步  rsync://distfiles.gentoocn.org/gentoo-zh 到 mirror.nju.edu.cn/gentoo-zh

**Comment by peeweep** [comment]
> 同步完成 rsync://distfiles.gentoocn.org/gentoo-zh 到 mirror.nju.edu.cn/gentoo-zh 请测试是否可用

你好，rsync://mirror.nju.edu.cn/gentoo-zh 可用了， https://mirror.nju.edu.cn/gentoo-zh/distfiles/  还无法访问，可否将 https 一并提供？

> 另外是否可以请您将我这里的相关镜像加入到官方镜像列表中？

可以的，感谢

**Comment by yaoge123** [comment]
> > 同步完成 rsync://distfiles.gentoocn.org/gentoo-zh 到 mirror.nju.edu.cn/gentoo-zh 请测试是否可用
> 
> 你好，rsync://mirror.nju.edu.cn/gentoo-zh 可用了， https://mirror.nju.edu.cn/gentoo-zh/ 下的 distfiles 目录还无法访问。
现在好了
> 
> > 另外是否可以请您将我这里的相关镜像加入到官方镜像列表中？
> 
> 可以的，感谢
谢谢您！

**Comment by peeweep** [comment]
谢谢，https rsync 都可以正常用了。

**Comment by peeweep** [comment]
@yaoge123 Gentoo-zh 最近更新了域名，新的域名是 distfiles.gentoozh.org （ rsync 仓库为 rsync://distfiles.gentoozh.org/gentoo-zh ），旧的域名 distfiles.gentoocn.org 随时会删除解析，麻烦您更新一下

**Comment by yaoge123** [comment]
多谢提醒 已经更新为 rsync://distfiles.gentoozh.org/gentoo-zh/ 并且正常完成了同步
