### ISSUE TITLE
[MER] Mirror Error Report for Notepad2-zufuliu

### ISSUE THREAD

**Issue by Mikachu2333** [nju-lug/NJU-Mirror-Issue#53]
## Note

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to  the front-end.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.

## Error Information

Notepad2-zufuliu 已改名为 Notepad4。地址：https://github.com/zufuliu/notepad4

**Comment by yaoge123** [comment]
感谢提醒，已更正

**Comment by Mikachu2333** [comment]
@yaoge123 还没更正啊

![Screenshot_2024-10-02-12-04-42-097_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/674ee5ae-2ed6-43dd-932d-6ac9694b729f)

**Comment by yaoge123** [comment]
啊啊啊  忘了改link了
