### ISSUE TITLE
[MER] freebsd-pkg 源故障

### ISSUE THREAD

**Issue by ykla** [nju-lug/NJU-Mirror-Issue#54]
目前仓库的同步文件没有十月份的。<https://mirrors.nju.edu.cn/freebsd-pkg/FreeBSD%3A15%3Aamd64/latest/>

应该是目前追踪的上游宕掉了。请参见 <https://github.com/ustclug/discussions/issues/476>.

另外烦请同步下路径下的  `data.pkg`、`data.txz`。

**Comment by yaoge123** [comment]
我是从ustc同步的，现在ustc还在同步中，等ustc同步完后我这里才能同步到最新版

**Comment by yaoge123** [comment]
现在应该正常了，跟上ustc的同步了
