### ISSUE TITLE
[NMR] New Mirror Request for [Name]

### ISSUE THREAD

**Issue by yjdyamv** [nju-lug/NJU-Mirror-Issue#56]
## Note 

- [x ] **I understand that irregular questions may be rejected.**
- [ x] I understand that the issue raised here is **not** related to the front-end.
- [ x] I have looked it up in the NJU mirror, it's **not** in there now.
- [x ] I have looked it up in opening issue, it's **not** suggested by others.
- [x ] I have looked it up in closed issue, it's **not refused** by @yaoge123 for some reasons.
- [x ] I'm willing to add an NJU-mirror description to the original repo.

https://winlibs.com/

**Comment by yaoge123** [comment]
这个网页无法镜像
对 https://github.com/brechtsanders/winlibs_mingw 的releases镜像？但是可能不一定完整

**Comment by yjdyamv** [comment]
也可以啊，这个挺好的。只要镜像后能高速下载mingw64就可以了。

**Comment by yaoge123** [comment]
https://mirror.nju.edu.cn/github-release/brechtsanders/winlibs_mingw/

**Comment by yjdyamv** [comment]
😀芜湖，感谢。不愧是南大镜像站👍
