### ISSUE TITLE
[NMR] New Mirror Request for BioArchLinux

### ISSUE THREAD

**Issue by starsareintherose** [nju-lug/NJU-Mirror-Issue#6]
## Note 

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to the front-end.
- [x] I have looked it up in the NJU mirror, it's **not** in there now.
- [x] I have looked it up in opening issue, it's **not** suggested by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for same reasons.
- [x] I'm willing to add an NJU-mirror description to the original repo.

## Normal Repo
This is a Bioinformatics repository for Arch Linux and Arch Linux based repository

- git repo: https://github.com/BioArchLinux/Packages
- Size: 28G
- [ ] url_here: https://repo.malacology.net

**Comment by yaoge123** [comment]
Is it possible to synchronize via rsync? @starsareintherose

**Comment by starsareintherose** [comment]
Right, it's possible, but it needs a key, I can configure it.

**Comment by starsareintherose** [comment]
```
rsync -ravz [bio@bioarchlinux.org](mailto:bio@bioarchlinux.org)::sync/ destdir
```

**Comment by yaoge123** [comment]
http://mirror.nju.edu.cn/bioarchlinux/ 
https://mirror.nju.edu.cn/bioarchlinux/ 
rsync://mirror.nju.edu.cn/bioarchlinux/

**Comment by starsareintherose** [comment]
Thanks
