### ISSUE TITLE
[NMR] New Mirror Request for Java Scoop Bucket

### ISSUE THREAD

**Issue by LittleboyHarry** [nju-lug/NJU-Mirror-Issue#7]
## Note 

- [x] **I understand that irregular questions may be rejected.**
- [x] I understand that the issue raised here is **not** related to the front-end.
- [x] I have looked it up in the NJU mirror, it's **not** in there now.
- [x] I have looked it up in opening issue, it's **not** suggested by others.
- [x] I have looked it up in closed issue, it's **not refused** by @yaoge123 for same reasons.
- [x] I'm willing to add an NJU-mirror description to the original repo.

## Git Source Code

- [ ] https://github.com/ScoopInstaller/Java

  A Windows Scoop bucket, include multiple versions JDKs such as Oracle Java, OpenJDK, Eclipse Temurin, IBM Semeru, Zulu, ojdkbuild, Amazon Corretto, BellSoft Liberica, SapMachine and Microsoft JDK.

**Comment by LittleboyHarry** [comment]
@iori2333
@LadderOperator
@d-w-x 
请帮忙反馈一下？

**Comment by yaoge123** [comment]
https://mirror.nju.edu.cn/git/scoop-java.git/

**Comment by yaoge123** [comment]
好了 https://mirror.nju.edu.cn/git/scoop-java.git
