### ISSUE TITLE
[MER] Mirror Error Report for [Termux]

### ISSUE THREAD

**Issue by 2096779623** [nju-lug/NJU-Mirror-Issue#8]
## Note

- [X] **I understand that irregular questions may be rejected.**
- [X] I understand that the issue raised here is **not** related to  the front-end.
- [X] I have looked it up in opening issue, it's **not** reported by others.
- [X] I have looked it up in closed issue, it's **not refused** by @yaoge123 for same reasons.

## repo url

https://mirrors.nju.edu.cn/termux/

## error information

https://github.com/termux/termux-packages/issues/13977

与termux服务器不同步，修改日期对不上，最近的更新是在2021-07-29。

## how to reproduce the problem

重新按照 [这里](https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories)的方式进行同步。

**Comment by d-w-x** [comment]
感谢您的报告，我们正在检查这个问题！

**Comment by yaoge123** [comment]
感谢反馈，已经按照您给出的同步方法重新同步了
